name: CSharp Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      - name: Imposta .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Ripristina dipendenze
        run: dotnet restore

      - name: Build (controllo errori)
        run: dotnet build --no-restore

      - name: Scansione sicurezza
        run: semgrep scan --config=p/csharp
